<?php

use Illuminate\Database\Seeder;

class BsNodeSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $date=date('Y-m-d H:i:s');
        $data=[
            [
                'title'=>'后台首页',
                'uses'=>'App\\Http\\Controllers\\Admin\\IndexController@index',
                'controller'=>'App\\Http\\Controllers\\Admin\\IndexController',
                'relates'=>'',
            ],
            [
                'title'=>'修改密码',
                'uses'=>'App\\Http\\Controllers\\Admin\\IndexController@setPwd',
                'controller'=>'App\\Http\\Controllers\\Admin\\IndexController',
                'relates'=>'App\\Http\\Controllers\\Admin\\IndexController@setPwdHandle',
            ],
            [
                'title'=>'资料设置',
                'uses'=>'App\\Http\\Controllers\\Admin\\IndexController@setInfo',
                'controller'=>'App\\Http\\Controllers\\Admin\\IndexController',
                'relates'=>'App\\Http\\Controllers\\Admin\\IndexController@setInfoHandle',
            ],
            [
                'title'=>'列表',
                'uses'=>'App\\Http\\Controllers\\Admin\\AdminController@index',
                'controller'=>'App\\Http\\Controllers\\Admin\\AdminController',
                'relates'=>'',
            ],
            [
                'title'=>'新建',
                'uses'=>'App\\Http\\Controllers\\Admin\\AdminController@create',
                'controller'=>'App\\Http\\Controllers\\Admin\\AdminController',
                'relates'=>'App\\Http\\Controllers\\Admin\\AdminController@store',
            ],
            [
                'title'=>'修改',
                'uses'=>'App\\Http\\Controllers\\Admin\\AdminController@edit',
                'controller'=>'App\\Http\\Controllers\\Admin\\AdminController',
                'relates'=>'App\\Http\\Controllers\\Admin\\AdminController@update',
            ],
            [
                'title'=>'启用',
                'uses'=>'App\\Http\\Controllers\\Admin\\AdminController@enable',
                'controller'=>'App\\Http\\Controllers\\Admin\\AdminController',
                'relates'=>'',
            ],
            [
                'title'=>'禁用',
                'uses'=>'App\\Http\\Controllers\\Admin\\AdminController@disable',
                'controller'=>'App\\Http\\Controllers\\Admin\\AdminController',
                'relates'=>'',
            ],
            [
                'title'=>'删除',
                'uses'=>'App\\Http\\Controllers\\Admin\\AdminController@destroy',
                'controller'=>'App\\Http\\Controllers\\Admin\\AdminController',
                'relates'=>'',
            ],
            [
                'title'=>'列表',
                'uses'=>'App\\Http\\Controllers\\Admin\\RoleController@index',
                'controller'=>'App\\Http\\Controllers\\Admin\\RoleController',
                'relates'=>'',
            ],
            [
                'title'=>'新建',
                'uses'=>'App\\Http\\Controllers\\Admin\\RoleController@create',
                'controller'=>'App\\Http\\Controllers\\Admin\\RoleController',
                'relates'=>'App\\Http\\Controllers\\Admin\\RoleController@store',
            ],
            [
                'title'=>'修改',
                'uses'=>'App\\Http\\Controllers\\Admin\\RoleController@edit',
                'controller'=>'App\\Http\\Controllers\\Admin\\RoleController',
                'relates'=>'App\\Http\\Controllers\\Admin\\RoleController@update',
            ],
            [
                'title'=>'启用',
                'uses'=>'App\\Http\\Controllers\\Admin\\RoleController@enable',
                'controller'=>'App\\Http\\Controllers\\Admin\\RoleController',
                'relates'=>'',
            ],
            [
                'title'=>'禁用',
                'uses'=>'App\\Http\\Controllers\\Admin\\RoleController@disable',
                'controller'=>'App\\Http\\Controllers\\Admin\\RoleController',
                'relates'=>'',
            ],
            [
                'title'=>'删除',
                'uses'=>'App\\Http\\Controllers\\Admin\\RoleController@destroy',
                'controller'=>'App\\Http\\Controllers\\Admin\\RoleController',
                'relates'=>'',
            ],
            [
                'title'=>'列表',
                'uses'=>'App\\Http\\Controllers\\Admin\\NodeController@index',
                'controller'=>'App\\Http\\Controllers\\Admin\\NodeController',
                'relates'=>'',
            ],
            [
                'title'=>'新建',
                'uses'=>'App\\Http\\Controllers\\Admin\\NodeController@create',
                'controller'=>'App\\Http\\Controllers\\Admin\\NodeController',
                'relates'=>'App\\Http\\Controllers\\Admin\\NodeController@store',
            ],
            [
                'title'=>'修改',
                'uses'=>'App\\Http\\Controllers\\Admin\\NodeController@edit',
                'controller'=>'App\\Http\\Controllers\\Admin\\NodeController',
                'relates'=>'App\\Http\\Controllers\\Admin\\NodeController@update',
            ],
            [
                'title'=>'删除',
                'uses'=>'App\\Http\\Controllers\\Admin\\NodeController@destroy',
                'controller'=>'App\\Http\\Controllers\\Admin\\NodeController',
                'relates'=>'',
            ],
        ];
        foreach ($data as $v){
            \App\Model\Admin\Node::create($v);
        }
    }
}
